apiVersion: apps/v1
kind: Deployment
metadata:
  name: codestrands-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codestrands-backend
      version: v1
  template:
    metadata:
      labels:
        app: codestrands-backend
        version: v1
    spec:
      containers:
      - image: ghcr.io/noodlecases/codestrands-backend:6ffc166
        imagePullPolicy: IfNotPresent
        name: codestrands-backend
        ports:
        - containerPort: 8000
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: codestrands-secret
                key: database-url
                optional: false
          - name: REDIS_URL
            valueFrom:
              secretKeyRef:
                name: codestrands-secret
                key: redis-url
                optional: false
          - name: DEBUG
            valueFrom:
              secretKeyRef:
                name: codestrands-secret
                key: debug
                optional: false
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: codestrands-secret
                key: secret-key
                optional: false
          - name: OAUTH_REDIRECT_URI
            valueFrom:
              secretKeyRef:
                name: codestrands-secret
                key: oauth-redirect-uri
                optional: false
          - name: OAUTH_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: codestrands-secret
                key: oauth-client-id
                optional: false
          - name: OAUTH_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: codestrands-secret
                key: oauth-client-secret
                optional: false
          - name: OAUTH_URL
            valueFrom:
              secretKeyRef:
                name: codestrands-secret
                key: oauth-url
                optional: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: codestrands-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codestrands-frontend
      version: v1
  template:
    metadata:
      labels:
        app: codestrands-frontend
        version: v1
    spec:
      containers:
      - image: ghcr.io/noodlecases/codestrands-frontend:6ffc166
        imagePullPolicy: IfNotPresent
        name: codestrands-frontend
        ports:
        - containerPort: 3000
