apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - releaseName: noodlecases-keycloak
    namespace: noodlecases-auth
    name: keycloak
    repo: https://charts.bitnami.com/bitnami
    version: 13.0.2
    valuesFile: values.keycloak.yaml
    includeCRDs: true
